external_apis:
  api_key: # Thay bằng API key thực tế
  base_url: 

models:
  image:
    - name: "doubao-seedream-5-0-260128"
      type: "t2i"
      description: "Seedream 5.0 - Text to Image"
    - name: "doubao-seedream-5-0-260128"
      type: "i2i"
      description: "Seedream 5.0 - Image to Image"
    - name: "doubao-seedream-4-5-251128"
      type: "t2i"
      description: "Seedream 4.5 - Text to Image"
    - name: "doubao-seedream-4-5-251128"
      type: "i2i"
      description: "Seedream 4.5 - Image to Image"
    - name: "doubao-seedream-4-0-250828"
      type: "t2i"
      description: "Seedream 4.0 - Text to Image"
    - name: "doubao-seedream-4-0-250828"
      type: "i2i"
      description: "Seedream 4.0 - Image to Image"
    - name: "doubao-seededit-3-0-i2i-250628"
      type: "i2i"
      description: "Seedream 3.0 - Image to Image"
    - name: "doubao-seedream-3-0-t2i-250415"
      type: "t2i"
      description: "Seedream 3.0 - Text to Image"
    - name: "sora_image"
      type: "t2i"
      description: "Sora Image - Image to Image"
    - name: "sora_image"
      type: "i2i"
      description: "Sora Image - Image to Image"
   
  video:
    - name: "veo_3_1-fast"
      type: "video"
      description: "Veo 3.1 Fast - Video Generation"
    - name: "veo3.1-components"
      type: "video"
      description: "Veo 3.1 Components - Video Generation"
    - name: "veo3-fast-frames"
      type: "video"
      description: "Veo Fast Frames - Video Generation"